import { DM_Sans } from "next/font/google";
import "./globals.css";
import Header from "./components/header/Header";
import Footer from "./components/footer/Footer";
import AuthProvider from "@/providers/AuthProvider";
import { PostContextProvider } from "@/context/postContext/PostContext";

const dmSans = DM_Sans({ subsets: ["latin"] });

export const metadata = {
  title: "Lumina - Share Your Blog With Your Friends and Family",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link rel="shortcut icon" href="/images/logo.png" type="image/x-icon" />
      </head>
      <body className={dmSans.className}>
        <PostContextProvider>
          <AuthProvider>
            <div className="container">
              <Header />
              {children}
              <Footer />
            </div>
          </AuthProvider>
        </PostContextProvider>
      </body>
    </html>
  );
}
